/* Write your PL/SQL query statement below */
with CTE as(
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FRST_DATE
    FROM Activity
    GROUP BY PLAYER_ID),
CON AS(
    SELECT A.PLAYER_ID AS PLAYER_ID
    FROM Activity A
    JOIN
    cte ON A.PLAYER_ID = CTE.PLAYER_ID
    WHERE A.EVENT_DATE=CTE.FRST_DATE + 1
)
-- SELECT * FROM CTE;
-- SELECT * FROM CON;

SELECT ROUND(COUNT(DISTINCT CON.PLAYER_ID)/COUNT(CTE.PLAYER_ID),2) AS fraction FROM
CTE LEFT JOIN CON ON CON.PLAYER_ID = CTE.PLAYER_ID;
